export const GET_USER_LOGIN = "GET_USER_LOGIN";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_HOMEPAGE_PRODUCTS = "GET_HOMEPAGE_PRODUCTS";
export const GET_CARTS = "GET_CARTS";
export const GET_CART_ITEM = "GET_CART_ITEM";